CREATE OR REPLACE VIEW vw_orders AS
SELECT
    o.id,
    o.created_at,
    o.updated_at,
    o.created_by,
    o.updated_by,
    o.latitude,
    o.longitude,
    o.approved_at,
    o.approved_by,
    o.delivery_date,
    o.delivery_mode,
    o.discount_amount,
    o.invoice_photo_url,
    o.order_date,
    o.order_number,
    o.payment_mode_id,
    o.remarks,
    o.shop_id,
    o.shop_visit_id,
    o.status,
    o.subtotal,
    o.tax_amount,
    o.total_amount,
    o.transportation_mode_id,
    o.user_id,
    s.name AS shop_name,
    COALESCE(SUM(oi.line_total), o.total_amount) AS order_total,
    COUNT(oi.id) AS item_count
FROM orders o
LEFT JOIN order_items oi ON oi.order_id = o.id
LEFT JOIN shops s ON s.id = o.shop_id
GROUP BY
    o.id,
    o.created_at,
    o.updated_at,
    o.created_by,
    o.updated_by,
    o.latitude,
    o.longitude,
    o.approved_at,
    o.approved_by,
    o.delivery_date,
    o.delivery_mode,
    o.discount_amount,
    o.invoice_photo_url,
    o.order_date,
    o.order_number,
    o.payment_mode_id,
    o.remarks,
    o.shop_id,
    o.shop_visit_id,
    o.status,
    o.subtotal,
    o.tax_amount,
    o.total_amount,
    o.transportation_mode_id,
    o.user_id,
    s.name;
